global:
  resolve_timeout: 5m
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default
  routes:
  - match:
      alertname: DeadMansSwitch
    repeat_interval: 5m
    receiver: deadmansswitch
  - match:
      severity: critical
    receiver: itops
receivers:
- name: default
  email_configs:
    - send_resolved: true
      # Whether or not to notify about resolved alerts.
      # The email address to send notifications to.
      to: vijay@localmail.mevijay.com
      # The sender address.
      from: ocpalert@localmail.mevijay.com
      # The SMTP host through which emails are sent.
      smarthost: 192.168.1.5:25
      # The hostname to identify to the SMTP server.
      hello: localmail.mevijay.com
      # The SMTP TLS requirement.
      require_tls: false
- name: itops
  email_configs:
    - send_resolved: true
      # Whether or not to notify about resolved alerts.
      # The email address to send notifications to.
      to: vijay@localmail.mevijay.com
      # The sender address.
      from: vijay@localmail.mevijay.com
      # The SMTP host through which emails are sent.
      smarthost: 192.168.1.5:25
      # The hostname to identify to the SMTP server.
      hello: localmail.mevijay.com
      # The SMTP TLS requirement.
      require_tls: false
- name: deadmansswitch
