apiVersion: v1
kind: Pod
metadata:
  name: pv-pod2 
  labels:
    app: pv-pod2
spec:
  containers:
    - name: frontend
      image: veermuchandi/welcome
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
      ports:
        - containerPort: 8080
  volumes:
   - name: mypd
     persistentVolumeClaim:
      claimName: claim1
