apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl 
            image: debianmaster/kubectl
            args:
            - /bin/sh
            - -c
            - kubectl apply -f https://raw.githubusercontent.com/debianmaster/openshift-examples/master/deployments/example1.yaml 
          restartPolicy: Never
