kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "dclaim1"
  annotations:
    volume.alpha.kubernetes.io/storage-class: "foo" 
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "3Mi"
