apiVersion: config.istio.io/v1alpha2
kind: denier
metadata:
  name: handler
  namespace: default
spec:
  status:
    code: 7 # https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
    message: Not allowed  # This message is sent back the client
---
apiVersion: config.istio.io/v1alpha2
kind: checknothing
metadata:
  name: denyrequest
  namespace: default
spec:
---

