apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: openshift-slack
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"": "myphp", "namespace": "", "kind":
        "DeploymentConfig"}]'
    creationTimestamp: null
    labels:
      name: openshift-slack-pipeline
    name: openshift-slack-pipeline
  spec:
    nodeSelector: null
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: None
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |
          node() {
          stage 'build'
          try {
          openshiftBuild(buildConfig: 'docker-nginx', showBuildLogs: 'true')
          } catch(err) {
                slackSend (color: '#FFFF00', message: "Failed: Job")
                error "Program failed, please read logs..."
          }
          stage 'deploy'
          try {
          openshiftDeploy(deploymentConfig: 'docker-nginx')
          openshiftScale(deploymentConfig: 'docker-nginx',replicaCount: '2')
          } catch(err) {
                slackSend (color: '#FFFF00', message: "Failed: Job")
                error "Program failed, please read logs..."
          }

          }
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
  status:
    lastVersion: 0
