apiVersion: v1
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: xxxxxxx
        server: https://192.168.1.15:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kubernetes-admin
      name: kubernetes-admin@kubernetes
    current-context: kubernetes-admin@kubernetes
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: xxxxxxxxx
        client-key-data: xxxxxxxxx
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: octant-ctx
